# Binance Trading Bot Configuration

# Top coin selection
top_coins_count: 20

# Position sizing
position_size_usd: 100.0

# Risk Management
stop_loss_percent: 2.0
trailing_stop_percent: 1.5

# Timeframe for technical analysis
timeframe: 15m

# Technical Indicators
indicators:
  stoch_rsi:
    period: 14
  
  heiken_ashi:
    enabled: true
  
  ichimoku:
    tenkan_period: 9
    kijun_period: 26
    senkou_period: 52
  
  moving_averages:
    short_period: 20
    long_period: 50
  
  ema:
    fast_period: 12
    slow_period: 26
  
  bollinger:
    period: 20
    std_dev: 2
  
  atr:
    period: 14
  
  adx:
    period: 14

# Trading Settings
check_interval_seconds: 60
max_open_positions: 20

# Signal Generation
signal_thresholds:
  volume_spike: 1.5
  adx_strong_trend: 25
  bb_squeeze: 0.02

# Binance API (set in .env file)
testnet: false
