# Binance Trading Bot Configuration

# Top coin selection
top_coins_count: 20

# Position sizing
position_size_usd: 100.0

# Risk Management
stop_loss_percent: 2.0
trailing_stop_percent: 1.5

# Timeframe for technical analysis
timeframe: 15m

# Parabolic SAR Indicator
parabolic_sar:
  acceleration: 0.02
  maximum: 0.2

# Classic Pivot S3 Support Filter
classic_pivot:
  lookback_candles: 5      # Number of recent candles to check for S3 test
  tolerance_percent: 0.5   # % tolerance for "approaching" S3 (0.5% = S3 ± 0.5%)

# Trading Settings
check_interval_seconds: 60
max_open_positions: 20

# Binance API (set in .env file)
testnet: false
