# Binance Trading Bot Configuration

# Top coin selection
top_coins_count: 20

# Position sizing
position_size_usd: 100.0

# Risk Management
stop_loss_percent: 2.0
trailing_stop_percent: 1.5

# Timeframe for technical analysis
timeframe: 15m

# Moving Average Indicator (for 15m timeframe)
moving_averages:
  fast: 9        # MA 9
  medium: 21     # MA 21
  slow: 49       # MA 49

# Daily Pivot Point Filter
daily_pivot:
  lookback_candles: 20     # Number of recent 15m candles to check for pivot test (~5 hours)
  tolerance_percent: 0.5   # % tolerance for "approaching" pivot (0.5% = P ± 0.5%)

# Trading Settings
check_interval_seconds: 60
max_open_positions: 20

# Binance API (set in .env file)
testnet: false
